tryber/sd-08-project-recipes-app

package-lock.json
src/App.js
src/components/Card/Card.css
src/components/Card/index.js
src/pages/Drinks/DrinkDetails.js
src/pages/Drinks/DrinkInProgress.js
src/pages/Drinks/Drinks.js
src/pages/Drinks/index.js
src/pages/Foods/FoodDetails.js
src/pages/Foods/FoodInProgress.js
src/pages/Foods/Foods.js
src/pages/Foods/index.js
src/pages/Login/index.js
src/pages/Profile/index.js
src/routes/routes.js

Alinhando e Iniciando o  Projeto

[Grupo 08] Commit Inicial

---

package.json
src/App.js
src/Pages/localstoragem

Main group 20 inicio

---

package-lock.json
src/App.js
src/Components/Button.js
src/Components/Input.js
src/Components/index.js
src/Pages/Login.js

Adiciona input de email e senha e um botao de entrar na tela de login

Requisito 2 

---

package-lock.json
src/App.js
src/context/Context.js
src/context/Provider.js
src/index.js

[Grupo 7] Estrutura Inicial

---

src/Components/Button.js
src/Pages/Login.js

Feito a validação e criação do estado no componente login

Main group 20 req 3 4 5

---

package-lock.json
src/App.js
src/context/Context.jsx
src/context/Provider.jsx
src/redux/actions.js
src/redux/reducers.js
src/redux/store.js

Main group 23 criacao de rotas

Main group 23 criacao de rotas

---

src/App.js
src/context/Context.js
src/context/Provider.js
src/index.js
src/pages/Login.js

[Grupo 5]iniciando o projeto e abrindo pull request

---

cypress/integration/login_spec.js
src/pages/Login/index.js

Realiza a verificação de email e senha no formulario de login e redireciona para a rota /comidas

[Main Group 8] - Requisitos 3 a 8

---

src/App.js
src/context/Provider.js
src/index.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/DetalhesBebida.js
src/pages/DetalhesComida.js
src/pages/Explorar.js
src/pages/ExplorarBebidas.js
src/pages/ExplorarComidas.js
src/pages/IngredientesBebidas.js
src/pages/IngredientesComidas.js
src/pages/Login.js
src/pages/NaoEncontrada.js
src/pages/OrigemComidas.js
src/pages/Perfil.js
src/pages/ProcessoBebida.js
src/pages/ProcessoComida.js
src/pages/ReceitasFavoritas.js
src/pages/ReceitasFeitas.js
src/services/RequisicaoApi.js

[Grupo 7] Rotas e Serviços

---

src/App.js
src/components/Login.jsx
src/index.js
src/pages/LoginPage.js

Conclui o req 5 e cria a estrutura para as rotas.

[GROUP 10] - req 5

---

package-lock.json
src/App.js
src/context/Provider.js
src/pages/Login.js

Tela de login, sem css, requisito 02 ao 08. Funções transportadas para a page/Login.js

Main group 13 login screen fixed

---

package-lock.json
src/App.js
src/context/Provider.js
src/pages/Login.js

Tela de Login feita, sem css, pegando do requisito 02 ao requisito 08.

Login screen - req02-req08

---

src/App.js
src/component/Header.js
src/pages/Drinks/DrinkDetails.js
src/pages/Drinks/DrinkInProgress.js
src/pages/Drinks/Drinks.js
src/pages/Drinks/index.js
src/pages/Explore/Explore.js
src/pages/Explore/ExploreByOrigin.js
src/pages/Explore/ExploreDrinks.js
src/pages/Explore/ExploreDrinksByIngredient.js
src/pages/Explore/ExploreFoods.js
src/pages/Explore/ExploreFoodsByIngredient.js
src/pages/Explore/index.js
src/pages/Foods/FoodDetails.js
src/pages/Foods/FoodInProgress.js
src/pages/Foods/Foods.js
src/pages/Foods/index.js
src/pages/Profile.js
src/pages/Recipes/RecipesDone.js
src/pages/Recipes/RecipesFavorite.js
src/pages/Recipes/index.js

Finalizado os requisitos 9 ao 12 sem css

Main group 13 header - Req 9 ao 12

---

src/App.js
src/component/Header.js
src/component/RecipesCard.js
src/component/SearchBar.js
src/context/Provider.js
src/pages/Drinks/DrinkDetails.js
src/pages/Drinks/DrinkInProgress.js
src/pages/Drinks/Drinks.js
src/pages/Drinks/index.js
src/pages/Explore/Explore.js
src/pages/Explore/ExploreByOrigin.js
src/pages/Explore/ExploreDrinks.js
src/pages/Explore/ExploreDrinksByIngredient.js
src/pages/Explore/ExploreFoods.js
src/pages/Explore/ExploreFoodsByIngredient.js
src/pages/Explore/index.js
src/pages/Foods/FoodDetails.js
src/pages/Foods/FoodInProgress.js
src/pages/Foods/Foods.js
src/pages/Foods/index.js
src/pages/Profile.js
src/pages/Recipes/RecipesDone.js
src/pages/Recipes/RecipesFavorite.js
src/pages/Recipes/index.js
src/services/apiRequests.js

Finalizados requisitos 13 ao 18.
Contém também os requisitos 9 ao 12.

Main group 13 search bar header req 13 to 18

---

cypress/integration/header_search_bar_spec.js
src/App.js
src/api/fetchDrinksAPI.js
src/api/fetchMealsAPI.js
src/api/getResultFromAPI.js
src/components/Button.js
src/components/Header.js
src/components/Inputs.js
src/context/Provider.jsx
src/pages/Bebidas.jsx
src/pages/Comidas.jsx

Requisitos  13, 14 e 15. 
Falta ver a questao do lint nao deixar ter "alert"

Main group 23 api

---

src/App.js
src/components/Header.jsx
src/components/RecipeSearchBar.jsx
src/pages/MainRecipes.js
src/pages/ProfilePage.js

Req - 9 - Implemente os elementos do header na tela principal de receitas, respeitando os atributos descritos no protótipo
Req - 10 - Implemente um ícone para a tela de perfil, um título e um ícone para a busca, caso exista no protótipo

first commit req. 9

---

package-lock.json
src/context/userContext/UserProvider.js
src/pages/login/index.js

- Adicionado campo para digitar senha e botão de entrar

[Group-4][Req-02]

---

src/components/HeaderPS.js
src/components/RecipeList.js
src/context/Provider.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Login.js
src/services/RequisicaoApi.js
src/styles/RecipeList.css

[Grupo 7] Requisitos 13-18

---

src/components/Card/index.js
src/components/Header/index.js
src/components/Search/index.js
src/context/ContextFood.js
src/pages/Drinks/Drinks.js
src/pages/Foods/Foods.js
src/services/api.js

- Cria o redirecionamento para a pagina de detalhes da comida e bebida caso apenas um seja encontrado, para isso utiliza o Redirect em uma renderização condicional na pagina de Comidas e na de Bebidas ( mesma logica, só muda o nome dos elementos. 
- Limita a exibição dos cards a um total de 12 utilizando um filter antes do map para renderizar os cards. No componente card foi necessario colocar data-testids que nao estao no readme, na div do card, no nome e na imagem do card.

Main group 8 req16e17

---

src/components/Header/index.js
src/components/Search/index.js
src/context/ContextFood.js
src/pages/Drinks/Drinks.js
src/pages/Foods/Foods.js
src/services/api.js

- Refatora as chamadas para a api para as funções funcionarem de forma dinamica de acordo com a pagina atual (comidas ou bebidas). 
- Essa informação esta sendo setada no estado local do componente de contexto. 
- Ela é setada pelo componente Header que recebe via uma prop chamada currentPage (Foods/ Drinks), e ao ser atualizado, altera a informação no contexto atraves de um useEffect, o que gera novas requisições para a Api de acordo com a pagina na qual o Header esta sendo renderizado.

Main group 8 req15

---

src/component/Footer.js
src/component/index.js
src/pages/Drinks/Drinks.js
src/pages/Explore/Explore.js
src/pages/Explore/ExploreByOrigin.js
src/pages/Explore/ExploreDrinks.js
src/pages/Explore/ExploreDrinksByIngredient.js
src/pages/Explore/ExploreFoods.js
src/pages/Explore/ExploreFoodsByIngredient.js
src/pages/Foods/Foods.js
src/pages/Profile.js

[GRUPO 13] REQUISITOS 19-24

---

src/index.js
src/pages/Login/index.js
src/services/localStorage.js

Passando no requisito 7, correção da função de setar o localStorage, necessário finalizar requisito 5 para passar nos testes.

Requisito 7 concluído, necessário finalizar requisito 5

---

src/index.js
src/pages/Login/index.js
src/services/localStorage.js

Passando no Requisito 6, porém e necessário o req05.
Criação da pasta services.

[Cuscus-Redux][REQ06][FEAT]

---

package-lock.json
src/pages/Login/index.js

Cuscuz redux req05

---

src/pages/login/index.js

- Adicionado verificações de e-mail e senha.

[Group-4][Req-05]

---

src/App.js
src/Components/Input.js
src/Pages/Comidas.js
src/Pages/Login.js
src/Pages/localstoragem

Implementado as informações no localStorage e o redirect para comidas

Main group 20 req 6 7 8

---

cypress/integration/header_spec.js
src/App.js
src/components/Header.js
src/context/ContextRecipes.js
src/context/ProviderRecipes.js
src/pages/Perfil.js

Main group 17 Quesito 11

---

cypress/integration/header_search_bar_spec.js
cypress/integration/login_spec.js
src/components/Header.js
src/pages/Login.jsx

refatora handle click e a ver o alert com linter

[GRUPO 23] TEAM DILLY FTW 

---

src/App.js
src/index.css
src/pages/Perfil.js
src/styles/Login.css
src/styles/Perfil.css

[Grupo 7] - Tela de Perfil

---

src/App.js
src/components/Card.js
src/components/Footer.js
src/components/Header.js
src/components/SeachBar.js
src/index.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Explorar.js
src/pages/Login.js
src/pages/PerfilPágina.js
src/routes/index.js

Main group 3 estruturaçao de paginas

---

src/pages/login/index.js

- Adicionado requisitos 6 ao 8, guardar dados no LocalStorage e redirecionar para página "/comidas"

[Group-4][Req-06-08]

---

package-lock.json
src/App.js
src/ContextApi/RecipesContext.js
src/ContextApi/RecipesProvider.js
src/components/TextInput.js
src/index.js
src/pages/Login.js
src/pages/RecipesFood.js

Requisito de 01 ao 08, criado a pagina de Login.

Requisito do 01 ao 08

---

src/components/Header/index.js
src/components/SeekBar/index.js

Requisito 13 feito

---

cypress/integration/header_search_bar_spec.js
cypress/integration/header_spec.js
src/App.js
src/api/getResultFromAPI.js
src/components/Header.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/pages/index.js

Finalizado requisitos 16/17/18.

Main-group-23 [Header Finalizado]

---

src/App.js
src/pages/perfil/index.js

- Adicionado tela completa de perfil

[Group-4][Req-82-87]

---

src/App.js
src/Components/Buttons/DefaultSearch.js
src/Pages/Bebidas.js
src/Pages/Explorar.js
src/Pages/ExplorarBebidas.js
src/Pages/ExplorarComidas.js
src/Pages/ExplorarIngredientes.js
src/Pages/ExplorarOrigem.js
src/Pages/Header.js
src/Pages/Perfil.js
src/Pages/ReceitasFavoritas.js
src/Pages/ReceitasFeitas.js
src/Pages/index.js

Grupo 20 - Requisitos 10 e 11

---

src/Pages/Bebidas.js
src/Pages/Comidas.js
src/Pages/Explorar.js
src/Pages/ExplorarBebidas.js
src/Pages/ExplorarComidas.js
src/Pages/ExplorarIngredientes.js
src/Pages/ExplorarOrigem.js
src/Pages/Footer.js
src/Pages/Perfil.js

implementação o footer nas telas do app de receita.

Requisito 19 ao 24

---

src/Routes.js
src/pages/DrinkDetails.jsx
src/pages/DrinkProcess.jsx
src/pages/Drinks.jsx
src/pages/DrinksExplore.jsx
src/pages/Explore.jsx
src/pages/ExploreDrinksIngredients.jsx
src/pages/ExploreFood.jsx
src/pages/ExploreFoodsLocal.jsx
src/pages/FavoritesRecipes.jsx
src/pages/FoodDetails.jsx
src/pages/FoodExploreIngredients.jsx
src/pages/FoodProcess.jsx
src/pages/Foods.jsx
src/pages/ReadyMadeRecipes.jsx

Ficou com todas as rotas funcionando e com Cabeçalho também.

todas as paginas no projeto com o header

---

src/components/SeekBar/index.js

Pequenas atualizações no layout da barra de pesquisa.

Atualizaçoes da barra de pesquisa

---

cypress/integration/recipes_list_spec.js
src/api/fetchMealsAPI.js
src/context/Provider.jsx
src/pages/Bebidas.jsx
src/pages/Comidas.jsx

[Main group 23] Requisito 27 a 32

---

cypress/integration/footer_spec.js
src/App.js
src/components/Footer.js
src/index.css
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Explorar.js

- Adiciona requisitos 19 e 20;
- Adiciona requisitos 22, 23 e 24;

Requisitos do Footer -21

---

cypress/integration/header_search_bar_spec.js
cypress/integration/recipes_list_spec.js
src/App.css
src/App.js
src/api/fetchCategories.js
src/api/fetchDrinksAPI.js
src/api/fetchMealsAPI.js
src/api/getResultFromAPI.js
src/components/Footer.js
src/components/Header.js
src/context/Provider.jsx
src/index.css
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/DetalhesBebida.jsx
src/pages/Explorar.jsx
src/pages/Perfil.jsx
src/pages/Receitas.jsx
src/pages/index.js

[MAIN GROUP 23] [REQ 28~32]

---

cypress/integration/header_search_bar_spec.js
src/App.css
src/App.js
src/api/getResultFromAPI.js
src/components/Footer.js
src/components/Header.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/DetalhesBebida.jsx
src/pages/Explorar.jsx
src/pages/Perfil.jsx
src/pages/Receitas.jsx
src/pages/index.js

Falta a implementacao das paginas de "Explorar" para que o requisito 21 passe no teste.

[Group 23] Footer Criado

---

cypress/integration/header_spec.js
src/components/Footer/index.js
src/components/Footer/style.css
src/components/SeekBar/index.js
src/pages/Foods/index.js

[Cuscuz-Redux][REQ19-20]

---

package-lock.json
package.json
src/components/Header.js
src/components/InputRadio.js
src/components/InputText.js
src/components/MainHeader.css
src/components/Search.css
src/components/SearchButton.js
src/components/Searchbar.js
src/context/index.js
src/hooks/index.js
src/pages/MainDrinks.js
src/pages/MainFoods.js
src/services/apiRequest.js

G12 - REQS 13 to 18

---

src/api/getResultFromAPI.js
src/components/Details.jsx
src/components/Header.js
src/context/Provider.jsx
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/services/createIngredientsArray.js

Header arrumado

---

src/Pages/Login.js
src/store/index.js
src/store/loginSlice.js
src/store/tempCodeRunnerFile.js

refatorando

---

src/component/SearchBar.js
src/pages/Drinks/Drinks.js
src/pages/Foods/Foods.js
src/pages/Profile.js

Criação da tela de perfil, cobrindo do requisito 82 ao 87, sem css.

Profile screen - req82-req87

---

src/App.css
src/components/Footer/Footer.css
src/components/Footer/index.js
src/pages/Drinks/Drinks.js
src/pages/Explorer/Explorer.js
src/pages/Explorer/ExplorerDrink.js
src/pages/Explorer/ExplorerDrinksIngredients.js
src/pages/Explorer/ExplorerFood.js
src/pages/Explorer/ExplorerFoodsIngredients.js
src/pages/Explorer/ExplorerFoodsRegion.js
src/pages/Foods/Foods.css
src/pages/Foods/Foods.js
src/pages/Profile/Profile.js
src/services/api.js

-Requisito funcionando e passando nos testes;
-Precisa fazer ajustes no css em relação ao posicionamento.
-Acho que vamos ter que usar media queries mesmo, porque como o requisito exige que o footer tenha position fixed, essa propriedade é sempre relativa ao viewport, entao quando estamos na visualização normal do navegador, ele extrapola o tamanho do body para pegar a largura de todo o navegador. Ja na visualização mobile ele fica posicionado corretamente

Main group 8 req19a24

---

src/components/ContainerDefault/index.js
src/components/Footer/index.js
src/pages/Profile/index.js
src/pages/RecipesMade/index.js

[Cuscuz-Redux][REQ's-82a87] 

---

src/component/SearchBar.js
src/pages/Drinks/Drinks.js
src/pages/Foods/Foods.js
src/pages/Profile.js

Concertado um problema de quando o localStorage com chave 'user' não existia.

Main group 13 hotfix profile page

---

src/components/ButtonLink.css
src/components/ButtonLink.js
src/components/RandomFood.js
src/context/index.js
src/pages/Explorer.js
src/pages/ExplorerDrinks.js
src/pages/ExplorerFods.js

Adds Features:
Redirection to explore, explore foods, explore drinks, surprise, explore by foods, explore origins

G12-REQ-67-73

---

src/components/CardFood.js
src/components/DrinkCategoryBar.js
src/components/FoodCategoryBar.js
src/context/bebidaContext/DrinkProvider.js
src/context/comidaContext/FoodProvider.js
src/index.css
src/pages/bebida/index.js
src/pages/comida/index.js
src/services/API.js

[Main Group 4] [Req 27]

---

src/pages/Recipes/RecipesDone.js

Tela de Receitas Feitas - req 54 ao 59

Main group 13 recipes done req 54 to 59

---

src/App.test.js
src/Routes.js
src/components/Header.js
src/components/TextInput.js
src/pages/drinks/Cocktails.js
src/pages/explorer/ExploreArea.js
src/pages/explorer/ExploreFood.js
src/pages/explorer/Explorer.js
src/pages/explorer/ExplorerCocktailIngredients.js
src/pages/explorer/ExplorerCocktails.js
src/pages/explorer/ExplorerFoodIngredients.js
src/pages/foods/FoodInProgress.js
src/pages/foods/RecipesFood.js
src/pages/user/DoneRecipes.js
src/pages/user/FavoriteRecipes.js
src/pages/user/Profile.js

Requisito 10

---

src/pages/Explorer/index.js

[Cuscuz-Redux][REQ-67a69]

---

src/pages/ExploreDrinks/index.js
src/pages/ExploreFoods/index.js
src/pages/Explorer/index.js

[Cuscuz-Redux][REQ-70a73]

---

src/components/Footer.js
src/components/HeaderP.js
src/components/HeaderPS.js
src/components/RecipeList.js
src/pages/Perfil.js
src/pages/ReceitasFeitas.js
src/styles/Footer.css
src/styles/HeaderP.css
src/styles/HeaderPS.css
src/styles/Login.css
src/styles/Perfil.css
src/styles/ReceitasFeitas.css
src/styles/RecipeList.css

[Grupo 7] - Tela de Receitas Feitas + base CSS

---

src/App.js
src/pages/Explorar.js
src/pages/ExplorarBebidas.js
src/pages/ExplorarComidas.js

Adicionar Requisitos da página Explorar

---

src/pages/receitas-feitas/index.js

- Implementando tela de receitas finalizadas

[Group-4][Req 54 ao 59]

---

cypress/integration/recipes_list_spec.js
src/App.css
src/components/Details.jsx
src/context/Provider.jsx
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/services/createIngredientsArray.js

[GRUPO 23] Req 32

---

src/pages/perfil/index.js
src/pages/receitas-favoritas/index.js

- Implementando tela de receitas favoritas

[Group-4][Req 60 ao 66]

---

src/pages/explorar/bebida/ingredientes/index.js
src/pages/explorar/comida/ingredientes/index.js
src/services/API.js

- Implementando tela de explorar ingredientes

[Group-4][Req-75 e 76]

---

src/components/CardDrink.js
src/components/CardFood.js
src/components/DrinkCategoryBar.js
src/components/FoodCategoryBar.js
src/components/SearchBarDrink.js
src/context/bebidaContext/DrinkProvider.js
src/context/comidaContext/FoodProvider.js
src/index.css
src/services/API.js

[Main group 4][Req 28-31]

---

src/api/getResultFromAPI.js
src/components/Header.js
src/context/Provider.jsx
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/Explorar.jsx
src/pages/ExplorarBebidas.jsx
src/pages/ExplorarComidas.jsx
src/pages/ExplorarOrigem.jsx
src/pages/IngredientesBebidas.jsx
src/pages/IngredientesComidas.jsx
src/pages/NotFound.jsx

Todos os requisitos ja testados,
Adicionado parametro novo no componente Header para desabilitar a funcao de filtragem em paginas que nao a utilizam

Finalizados Requisitos 67 a 81 - telas de explorar

---

src/components/DrinkCatsButtons.jsx
src/components/MealCatsButton.jsx
src/pages/DrinkRecipeDetails.js
src/pages/DrinksRecipes.js
src/pages/MealsRecipes.js
src/redux/actions/fetchDrinkCatsAction.js
src/redux/actions/fetchMealCatsAction.js
src/redux/actions/index.js
src/redux/reducers/recipesReducer.js
src/services/CocktailAPI.js
src/services/MealAPI.js

Requisito 27 - Implemente os botões de categoria para serem utilizados como filtro

first try req. 27

---

src/components/ButtonDefault.js
src/components/ButtonLink.css
src/components/Footer.js
src/components/SmallHolder.css
src/components/SmallHolder.js
src/pages/Profile.js

G12 profile 82 87

---

src/components/Header/index.js
src/components/SeekBar/index.js
src/pages/Drinks/index.js
src/redux/actions/index.js
src/redux/actions/types.js
src/redux/reducers/drinks.js
src/redux/reducers/food.js
src/redux/reducers/index.js
src/services/theCocTailDB.js

[Cuscuz-Redux][REQ15]

---

src/components/Header/index.js
src/components/SeekBar/index.js
src/pages/Drinks/index.js
src/pages/Foods/index.js
src/redux/actions/index.js
src/redux/actions/types.js
src/redux/reducers/drinks.js
src/redux/reducers/food.js
src/redux/reducers/index.js
src/services/theCocTailDB.js

[Cuscuz-Redux][REQ16]

---

src/components/Cards/index.js
src/components/Cards/style.css
src/components/CardsArea/index.js
src/components/Header/index.js
src/components/SeekBar/index.js
src/pages/Drinks/index.js
src/pages/Foods/index.js
src/redux/actions/index.js
src/redux/actions/types.js
src/redux/reducers/drinks.js
src/redux/reducers/food.js
src/redux/reducers/index.js
src/services/theCocTailDB.js

[Cuscuz-Redux][REQ17]

---

src/components/CardDrink.js
src/components/CardFood.js

[Main group 4][Req. 32]

---

src/context/globalContext/GlobalProvider.js
src/context/userContext/UserProvider.js
src/pages/login/index.js
src/pages/perfil/index.js
src/routes/index.js

- Arrumando requisitos 10 e 21

[Group-4][Corrigindo Requisitos]

---

src/pages/explorer/Explorer.js
src/pages/foods/RecipesFood.js

Apenas a pagina do explore pronta

Requisito da page Explore

---

src/context/ProviderReceitas.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/services/buscarCategoriasBebidas.js
src/services/buscarCategoriasComidas.js

Buttons de Categorias de Bebidas e Comidas

---

src/App.js
src/components/Details.jsx
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/pages/InProgressBebidas.jsx
src/pages/InProgressComida.jsx
src/pages/index.js
src/services/createIngredientsArray.js

req 35 pela metade, conferir com a ultima branch

[MAIN GROUP 23] [ Fix css]

---

src/App.css
src/components/RecomandationCard.js
src/pages/Bebidas.js
src/pages/ReceitasEmProgress.js
src/routes/index.js
src/services/index.js
src/utils/index.js

Dupla auge2

---

src/App.css
src/components/SearchDropDown.jsx
src/containers/Drinks.jsx
src/containers/MainFood.jsx
src/services/drinkBySearchFilter.js
src/services/fetchByFilter.js

Main group 1 requisitos 14 a 18

---

src/App.js
src/component/RecipeCards.js
src/component/index.js
src/pages/Drinks/Drinks.js
src/pages/Explore/ExploreByOrigin.js
src/pages/Explore/NotFound.js
src/pages/Foods/Foods.js
src/pages/Recipes/RecipesDone.js

Criação da Tela de explorar por local de origem/area, cobrindo do requisito 78 ao 81, sem css.

Explorer Origin  screen - req78-req81

---

src/App.js
src/components/ButtonSearch.jsx
src/components/RecipeSearchByArea.js
src/pages/ExploreOrigin.js
src/pages/NotFound.js
src/redux/actions/SelectAreaAction.js
src/redux/actions/fetchMealAction.js
src/redux/actions/index.js
src/redux/reducers/searchReducer.js

Requisitos 78 a 81 concluídos

---

src/App.js
src/components/Header.js
src/context/Provider.jsx
src/index.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/Explorar.jsx
src/pages/ExplorarBebidas.jsx
src/pages/ExplorarComidas.jsx
src/pages/ExplorarOrigem.jsx
src/pages/InProgressComidas.jsx
src/pages/IngredientesBebidas.jsx
src/pages/IngredientesComidas.jsx
src/pages/Login.jsx
src/pages/NotFound.jsx
src/pages/Perfil.jsx
src/pages/Receitas.jsx
src/pages/ReceitasFavoritas.jsx
src/pages/ReceitasFeitas.jsx
src/pages/index.js

Arrumado requisito 77
Logica da pagina de login alterada para resetar local storage
Pagina de Perfil adicionada 
Pagina de Receitas Feitas e Favoritas adicionada

Terminado requisitos 82 a 87 da pagina de perfil

---

public/index.html
src/App.css
src/api/getResultFromAPI.js
src/components/Details.jsx
src/components/RecomendationCard.jsx
src/components/Recomendations.jsx
src/pages/DetalhesBebida.jsx
src/redux/actions.js
src/redux/reducers.js
src/redux/store.js

[Group 23] Tela detalhes de receitas

---

src/pages/explorer/Explorer.js
src/pages/user/Profile.js

[main-group-24] - Pagina de Perfil Pronta

---

cypress/integration/recipe_in_progress_spec.js
src/components/CardRecipe/CardRecipe.js
src/components/CardRecipe/cardRecipe.css
src/pages/RecipesFavDone/RecipesFavDone.js
src/pages/RecipesFavDone/recipesFavDone.css
src/pages/RecipesInProgress/RecipesInProgress.js

Criação do componente cardRecipe que será reponsável por renderizar os item de receitas feitas ou favoritadas.

requisitos 53-54

---

src/containers/ExploreOrigination.jsx
src/core/Provider.js
src/services/filterMealByArea.js
src/services/index.js
src/services/listAreas.js

Main group 1 req 78-81

---

src/App.css
src/components/Details.jsx
src/components/RecomendationCard.jsx
src/components/Recomendations.jsx
src/context/Provider.jsx
src/css/Details.css
src/css/Recomendations.css
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/services/alternatePath.js
src/services/createIngredientsArray.js

Arrumei carousel e links do recommendation

Main group 23 req33 46

---

package-lock.json
package.json
public/index.html
src/App.css
src/App.js
src/components/Buttons/CategoryButtons.js
src/components/Buttons/ExploreByWhat.js
src/components/Buttons/index.js
src/components/Card/Card.css
src/components/Card/CarouselCard.js
src/components/Card/index.js
src/components/Footer/Footer.css
src/components/Header/index.js
src/components/Search/index.js
src/context/ContextDrink.js
src/context/ContextFood.js
src/pages/Drinks/DrinkDetails.js
src/pages/Drinks/Drinks.js
src/pages/Explorer/Explorer.js
src/pages/Explorer/ExplorerDrink.js
src/pages/Explorer/ExplorerFood.js
src/pages/Foods/FoodDetail.css
src/pages/Foods/FoodDetails.js
src/pages/Foods/Foods.css
src/pages/Foods/Foods.js
src/pages/hooks/useDrinkDetailsHook.js
src/pages/hooks/useFoodDetailsHook.js
src/services/api.js

Main group 8 reqs27a32 reforged

---

src/components/DoneAndFavRecipes/FavRecipe.js
src/components/DoneAndFavRecipes/RecipesContainer.js
src/components/DoneAndFavRecipes/styles.css
src/components/Header.js
src/pages/MainDrinks.js
src/pages/MainFoods.js
src/pages/RecipesFav.js
src/services/localStorage.js

G12 - Favorite Recipes Page - Requiriments-60-to-66

---

src/components/DrinkCatsButtons.jsx
src/components/MealCatsButton.jsx
src/components/RecipeSearchByArea.js
src/pages/DrinkIngredient.js
src/pages/DrinksRecipes.js
src/pages/ExploreOrigin.js
src/pages/FoodIngredient.js
src/pages/MealsRecipes.js

hotfix dispatch nas dependencias

---

src/App.js
src/components/LinkButton.js
src/context/Provider.js
src/pages/Explorar.js
src/pages/ExplorarBebidas.js
src/pages/ExplorarComidas.js
src/pages/IngredientesBebidas.js
src/pages/IngredientesComidas.js
src/pages/NaoEncontrada.js
src/pages/OrigemComidas.js
src/pages/Perfil.js
src/services/RequisicaoApi.js
src/styles/Ingredientes.css

Tela de explorar bebidas ou comidas
Tela de explorar por local de origem/area

[Grupo 7] Telas de Explorar

---

package-lock.json
package.json
src/App.css
src/App.js
src/components/RecommendedDrinks.js
src/components/RecommendedMeals.js
src/pages/DetalhesBebidas.js
src/pages/DetalhesComidas.js
src/pages/EmProgresso.js

[Grupo 5] Detalhes/Receitas Recomendadas

---

package-lock.json
package.json
src/components/Footer.js
src/components/HeaderPS.js
src/components/RecipeCategory.jsx
src/components/RecipeList.js
src/context/Provider.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Perfil.js

[Grupo 7] Merge Telas

---

src/components/Buttons/ExploreByWhat.js
src/pages/Drinks/Drinks.js
src/pages/Explorer/ExplorerDrink.js
src/pages/Explorer/ExplorerFood.js
src/pages/Explorer/ExplorerFoodsIngredients.js
src/pages/Explorer/ExplorerFoodsRegion.js
src/pages/Foods/Foods.js
src/services/api.js

Main group 8 reqs70a74

---

src/App.js
src/index.css
src/pages/Bebidas.js
src/pages/BebidasIngredientes.js
src/pages/Comidas.js
src/pages/ComidasIngredientes.js
src/pages/ExplorarBebidas.js
src/pages/ExplorarComidas.js
src/services/API.js

- 70-76;
- Requisito de clicar nos cards e ir para a página de detalhes;

Adiciona alguns requisitos aí

---

src/App.css
src/components/DoneRecipeCard.js
src/components/DrinksCard.js
src/components/FavoriteRecipeCard.js
src/components/RecipesCard.js
src/context/Provider.js
src/pages/DetalhesBebidas.js
src/pages/DetalhesComidas.js
src/pages/ReceitasFavoritas.js
src/pages/ReceitasFeitas.js

filtragem na tela de favoritas funcionando corretamente

[Grupo 5] Tela de receitas favoritas e feitas

---

src/components/DrinkInProgressCard.jsx
src/components/FoodInProgressCard.jsx
src/components/index.js
src/containers/DrinkDetailsInProgress.jsx
src/containers/ExploreOrigination.jsx
src/containers/FoodDetailsInProgress.jsx
src/core/Provider.js

Tela de receitas em progresso OK! (Faltando detalhe no requisito 51 a ser discutido com a instrução).

Main group 1 tela receitas progresso

---

src/components/FavoriteCard/FavoriteCard.jsx
src/components/FavoriteCard/styles.css
src/components/buttons/DoneAndFavoriteButtons.jsx
src/components/index.js
src/constants/index.js
src/containers/FavoriteRecipes.jsx
src/core/filtering.js

o requisito 66 é dividido em 2 partes... 1 parte não passou mas é devido a um erro no componente DrinkDetails que precisa ser refatorado

requisitos 60 a 66

---

README.md
src/components/index.js

Main group 1 fixing lint

---

src/pages/ExplorerFoodsDrinks/ExplorerFoodsDrinks.js
src/pages/ExplorerFoodsDrinks/explorerFoodsDrinks.css

Requisitos 70, 71 e 72 completos só erei no nome da branch mas ta valendo

Requisitos 70 a 72 completos

---

src/pages/ExpBebidasIngred.js
src/pages/ExpComidasIngred.js

[Grupo 5] Requisito77

---

src/components/Details.jsx
src/components/InProgressFood.jsx
src/components/ShareButton.js
src/css/InProgressFood.css
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/pages/InProgressBebidas.jsx
src/pages/InProgressComida.jsx
src/services/readLocalStorage.js
src/services/updateLocalStorage.js

Main group 23 in progress filipe

Main group 23 in progress filipe

---

cypress/integration/recipe_detail_spec.js
src/components/Button.js
src/components/Details.jsx
src/components/FavoriteButton.jsx
src/components/InProgressFood.jsx
src/components/YtVideo.jsx
src/css/InProgressFood.css
src/css/Recomendations.css
src/pages/DetalhesBebida.jsx
src/pages/DetalhesComida.jsx
src/pages/InProgressBebidas.jsx
src/pages/InProgressComida.jsx
src/services/readLocalStorage.js
src/services/updateLocalStorage.js

Arruma reqs quebrados, faz o 38 e att branch com a refatoração

[Group 23] req 38

---

src/components/DrinksButtonsFilter.js
src/components/DrinksList.js
src/components/MealsButtonsFilter.js
src/components/RecipesList.js
src/pages/Bebidas.js
src/pages/Comidas.js
src/pages/Perfil.js
src/services/apiRequests.js

Grupo-5-Requisitos-27-28-30-31

---

src/components/ExploreComponents/Drinks.js
src/components/ExploreComponents/Feed.js
src/components/ExploreComponents/Ingredients.js
src/components/ExploreComponents/Meals.js
src/components/ExploreComponents/NotFound.js
src/components/ExploreComponents/Origin.js
src/components/ExploreComponents/SurpriseMe.js
src/components/ExploreComponents/index.js
src/components/SearchBar/index.js
src/components/cards/DrinkCard.js
src/components/cards/MealCard.js
src/pages/Drinks/Drinks.js
src/pages/Explore/index.js
src/pages/Meals/Meals.js
src/services/API.js

Guys, 
- Pra concluir minha implementação eu fiz uma pequena alteração na tela principal de receitas, incluindo só uma verificação no `useEffect`.
- E no aproveitamento do Card, eu encapsulei a imagem dentro do botão, pra que o click que leva pros detalhes funcionasse na imagem também.

[Main Group 14] [Páginas de Explorar] [ Requisitos 67 - 81 ] 

---

cypress/integration/done_recipes_spec.js
package-lock.json
package.json
src/__tests__/Food.test.js
src/__tests__/Login.test.js
src/components/Buttons/CategoryButtons.js
src/components/DrinkDetailsInfo/index.js
src/components/FoodDetailsInfo/index.js
src/pages/Foods/FoodDetail.css
src/pages/Foods/Foods.js
src/pages/Profile/DoneRecipes.css
src/pages/Profile/DoneRecipes.js
src/pages/Profile/Profile.js

Aprovado nos testes;
Correções de css;

Requisito 54 aprovado

---

src/components/Card/CardFavorite.css
src/components/Card/CardFavorites.js
src/components/Header/index.js
src/pages/Profile/FavRecipes.js

Main group 8 req60a66

---

.eslintrc.json
package-lock.json
package.json
src/components/List/List.js
src/pages/Home/Home.js
src/pages/RecipesFavDone/RecipesFavDone.js
src/pages/RecipesFavDone/recipesFavDone.css
src/tests/Explorer.test.js
src/tests/RecipesFavDone.test.js
src/tests/helpers/renderWithRouter.js

Testes da tela Explorar

---

src/context/ProviderReceitas.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/ExplorarIngredientesBebidas.js
src/pages/ExplorarIngredientesComidas.js

Main group 16 req 77

---

src/components/CardsArea/index.js
src/components/FilterButton/index.js
src/components/FilterButtonsSection/index.js
src/pages/Drinks/index.js
src/pages/Foods/index.js

OBS: não estilizei os botões ainda.

[Cuscuz-Redux][REQ29a31]

---

src/components/Cards/index.js
src/components/DetailsHeader/index.js
src/components/FilterButton/index.js
src/components/FilterButtonsSection/index.js
src/components/InstructionsSection/index.js
src/components/RecipeButton/index.js
src/components/RecipeButton/styles.css
src/components/Recomendations/index.js
src/pages/Drinks/index.js
src/pages/DrinksDetails/index.js
src/pages/FoodDetails/index.js
src/services/theCockTailDB.js
src/services/theMeadlDB.js

[Cuscuz-Redux][Req33a38]

---

cypress/integration/done_recipes_spec.js
src/pages/Profile/DoneRecipes.js

Requisitos aprovados nos testes;
Tem um inline style que será removido quando definirmos os estilos definitos, esta ali apenas porque o teste nao passa sem CSS, pois exige que o centro da imagem esteja na tela para o evento de click;

Main group 8 req55a59

---

src/pages/Bebidas.js
src/pages/Comidas.js

Requisito 31 passa, 29 passa, e 30 não passa =(

[main-group-6] Requisito 31

---

src/pages/Foods/Foods.js

- Pequena correção na função onClick na linha 68 do componente Foods, estava faltando uma / no inicio do caminho de history.push, fazendo o redirecionamento cair no erro 404

corrige redirecionamento para a pagina de detalhes da comida

---

package-lock.json
package.json
src/components/DetailsHeader/index.js

[Cuscuz-Redux][Req43]

---

src/components/DoneCard/DoneCard.jsx
src/components/DoneCard/styles.css
src/components/index.js
src/containers/DoneRecipes.jsx

receitas feitas pronto, porém o requisito 59  não está passando assim como o o ultimo requisito da tela de favoritos por bug na página de drinkDetails e foodDetails

done recipes feitos porem o requisito 59 nao esta passando

---

src/App.css
src/App.js
src/components/DrinksCard.js
src/components/RecipesCard.js
src/pages/EmProgresso.js
src/pages/EmProgressoBebidas.js
src/pages/Login.js

[Grupo 5] Corrigindo requisitos

---

src/components/CardFavorites/index.js
src/components/ContainerWithoutFooter/index.js
src/components/DetailsHeader/index.js
src/components/FilterTypeButton/index.js
src/pages/FavoritesRecipes/index.js

[Cuscuz-Redux][Req60a66]

---

src/pages/ExploreDrinksByIngredient/index.js
src/pages/ExploreFoodByIngredient/index.js
src/services/theCockTailDB.js
src/services/theMeadlDB.js

[cuscuz-redux][requisito 75 e 76 ]

---

src/CSS/foodDetail.css
src/components/BeginContinueRecipeBtn.jsx
src/pages/FoodDetail.js

Requisitos 38, 39 e 40 concluidos.
Botão de iniciar receita foi componetizado.

Requisitos concluidos

---

src/components/DrinkCatsButtons.jsx
src/components/MealCatsButton.jsx

requisito 30 consertado

---

src/ContextApi/RecipesProvider.js
src/Routes.js
src/components/FoodCard.js
src/pages/NotFound.js
src/pages/explorer/ExploreArea.js
src/pages/foods/RecipesFood.js

Explore por area pronto

---

src/ContextApi/RecipesProvider.js

Exercicio explore area refatorado

---

src/components/Footer/index.js
src/pages/ExploreDrinks/index.js
src/pages/ExploreFoods/index.js
src/services/theCockTailDB.js
src/services/theMeadlDB.js

[Cuscuz-Redux][Req74]

---

cypress/integration/recipe_in_progress_spec.js
src/components/DetailsHeader/index.js
src/components/FinishButton/index.js
src/components/InstructionsInProgress/index.js
src/pages/DrinksProcess/index.js
src/pages/FoodProcess/index.js
src/pages/Login/index.js

[Cuscuz-Redux][Req47a53]

---

src/components/CardDoneRecipe/index.js
src/pages/Login/index.js
src/pages/RecipesMade/index.js

Esses requisitos são os finais(tirando o requisito 1).
**_Figth like the devil_**

[Cuscuz-Redux][Req55a59]

---

src/Routes.js
src/__tests__/login.test.js
src/containers/Login.jsx

finalizado testes da página de login

testes pagina de login finalizados

---

src/components/Card/Cards.js
src/components/Card/cards.css
src/components/CardDetail/CardDetail.js
src/components/CardDetail/cardDetail.css
src/components/CheckBoxIngredients/CheckBoxIngredients.js
src/components/Header/Header.js
src/components/Header/header.css
src/components/List/List.js
src/components/List/list.css
src/components/SearchBar/SearchBar.js
src/contextApi/Provider.js
src/pages/ExplorerByIngridients/ExplorerByIngridients.js
src/pages/NotFound/NotFound.js
src/routes.js

Reverts tryber/sd-08-project-recipes-app#887

Revert "New implementation"

---

src/components/CardReceitasFeitas.js
src/pages/ProgressoBebida.js
src/pages/ProgressoComida.js
src/pages/ReceitasFeitas.js
src/services/API.js

Requisitos 53, 54, 55, 56, 57, 58, 59

[main-group-6-tela de receitas]

---

src/__tests__/drinkDetailsInProgress.test.js
src/__tests__/exploreOrigination.test.js
src/__tests__/favoriteRecipes.test.js
src/__tests__/foodDetailsInProgress.test.js
src/__tests__/mainFood.test.js
src/__tests__/mocks/localStorageFavoriteRecipes.js
src/__tests__/notFound.test.js
src/__tests__/searchDropDown.test.js
src/components/FavoriteCard/FavoriteCard.jsx

All files                        |    72.43 |    50.43 |    68.22 |    73.16 |                   |
SearchDropDown.jsx             |    61.11 |        0 |    57.14 |    61.11 |... 23,24,25,49,75

Main group 1 unit tests
